import datetime
from datetime import datetime
from Cliente import Cliente
from Loja import Loja
i = ('\n\n---------------------------------------------\n')
f = ('\n---------------------------------------------')
cliente1 = Cliente('Juliana')
cliente2 = Cliente('Brian')
cliente3 = Cliente('Camila')
cliente4 = Cliente('Ana')
cliente5 = Cliente('Joao')
cliente6 = Cliente('Pedro')
loja1 = Loja('Bike legal', 10)
loja2 = Loja('Monster Bikes', 20)
loja3 = Loja('Bikes Bike', 5)
loja4 = Loja('Casa da Bike', 15)

print('TESTE CONSULTAR DISPONIBILIDADE DA LOJA')
print(f"{i}Exemplo de consulta - chamado na linha 20 {f}")
loja1.consultar_bike()
print('\n\n*********************************************************************************************#')
print('TESTE LOCACAO')
print(f"{i}Exemplo de sucesso na locacao - chamado na linha 24 {f}")
print(cliente1.alugar_bike(loja1, 5))
print(f"{i}Mostra que o cliente alugou 5 bikes - chamado na linha 26{f}")
print(cliente1)
print(f"{i}Loja agora so tem 5 bikes disponiveis - chamado na linha 28{f}")
print(loja1)
print(f"{i}Erro o cliente ja possui bikes alugadas - chamado na linha 30{f}")
print(cliente1.alugar_bike(loja1, 5))
print(f"{i}Erro a loja nao tem bikes o suficiente - chamado na linha  32{f}")
print(cliente2.alugar_bike(loja1, 7))
print(f"{i}Erro 'a' nao e uma quantidade valida- chamado na linha  34{f}")
print(cliente2.alugar_bike(loja1, 'a'))
print(f"{i}Erro loja nao existe - chamado na linha  36{f}")
print(cliente3.alugar_bike('loja4', 5))
print(f"{i}Erro quantidade negativa - chamado na linha  38{f}")
print(cliente3.alugar_bike(loja3, -5))
print('\n\n*********************************************************************************************#')
print('TESTE DEVOLUCAO')
print(f"{i}Erro nao possui bikes para devolver - chamado na linha 42 {f}")
print(cliente2.retornar_bike(loja1))
print(f"{i}Erro loja invalida - chamado na linha 45 {f}")
print(cliente3.alugar_bike(loja3, 5))
print(cliente3.retornar_bike('loja4'))
print(f"{i}Erro Cliente tentando devolver para uma loja diferente - chamado na linha 47 {f}")
print(cliente3.retornar_bike(loja2))
print(f"{i}Exemplo de sucesso na devolucao- chamado na linha 50 {f}")
cliente3.alugar_bike(loja3, 5)
print(cliente3.retornar_bike(loja3))
print('\n\n*********************************************************************************************#')
print('TESTE CONSULTA DE DEBITOS')
# FORCEI A MUDANCA DE HORARIO PARA TESTAR CALCULOS
print(f"{i}Erro cliente sem debito- chamado na linha 55 {f}")
print(cliente4.consultar_debito())
print(f"{i}Exemplo de sucesso na consulta de debitos - chamado na linha 57 {f}")
cliente2.alugar_bike(loja1, 1)
# FORCEI A MUDANCA DE HORARIO PARA TESTAR CALCULOS
cliente2._dtLocacao = datetime.strptime("2022-04-19 10:33", "%Y-%m-%d %H:%M")
print(cliente2.retornar_bike(loja1))
print(cliente2.consultar_debito())
print(f"{i}Exemplo de sucesso na consulta de debitos parciais- chamado na linha 66 {f}")
print(cliente4.alugar_bike(loja1, 2))
# FORCEI A MUDANCA DE HORARIO PARA TESTAR CALCULOS
cliente4._dtLocacao = datetime.strptime("2022-04-19 10:33", "%Y-%m-%d %H:%M")
print(cliente4.consultar_debito())
print('\n\n*********************************************************************************************#')
print('TESTE PAGAMENTO')
print(f"{i}Exemplo de sucesso no pagamento de debitos- chamado na linha 74 {f}")
print(cliente5.alugar_bike(loja1, 2))
# FORCEI A MUDANCA DE HORARIO PARA TESTAR CALCULOS
cliente5._dtLocacao = datetime.strptime("2022-04-14 10:33", "%Y-%m-%d %H:%M")
print(cliente5.retornar_bike(loja1))
print(cliente5.pagar_debito())
print(f"{i}Cliente agora sem debitos- chamado na linha 76 {f}")
print(cliente5)
print(f"{i}Erro tentando pagar locacao em aberto- chamado na linha 81 {f}")
print(cliente5.alugar_bike(loja3, 2))
# FORCEI A MUDANCA DE HORARIO PARA TESTAR CALCULOS
cliente5._dtLocacao = datetime.strptime("2022-04-20 10:33", "%Y-%m-%d %H:%M")
print(cliente5.pagar_debito())
